export const SET_ACTIVITY_CITYNAME = 'setActivityCityName'
export const SET_ACTIVITY_CITYID = 'setActivityCityId'
export const SET_UPLOAD_PARAM = 'setUploadParam'
export const UPLOAD_PHONE_BEFORE = 'uploadPhoneBefore'
export const UPLOAD_PHONE_SUCCESS = 'uploadPhoneSuccess'
export const UPLOAD_PHONE_ERROR = 'uploadPhoneError'