export default {
    "errno": 0,
    "data": {
        "BIGCITY": [
            {
                "city_id": "131",
                "name": "\u5317\u4eac",
                "pinyin": "BEIJING"
            }, {
                "city_id": "257",
                "name": "\u5e7f\u5dde",
                "pinyin": "GUANGZHOU"
            }, {
                "city_id": "289",
                "name": "\u4e0a\u6d77",
                "pinyin": "SHANGHAI"
            }, {
                "city_id": "340",
                "name": "\u6df1\u5733",
                "pinyin": "SHENZHEN"
            }
        ],
        "ABCDE": [
            {
                "city_id": "85",
                "name": "\u963f\u514b\u82cf\u5730\u533a",
                "pinyin": "AKESUDIQU"
            }, {
                "city_id": "731",
                "name": "\u963f\u62c9\u5c14\u5e02",
                "pinyin": "ALAERSHI"
            }, {
                "city_id": "230",
                "name": "\u963f\u62c9\u5584\u76df",
                "pinyin": "ALASHANMENG"
            }, {
                "city_id": "96",
                "name": "\u963f\u52d2\u6cf0\u5730\u533a",
                "pinyin": "ALETAIDIQU"
            }, {
                "city_id": "553",
                "name": "\u963f\u9c81\u79d1\u5c14\u6c81\u65d7",
                "pinyin": "ALUKEERQINQI"
            }, {
                "city_id": "446",
                "name": "\u5b89\u8fbe\u5e02",
                "pinyin": "ANDASHI"
            }, {
                "city_id": "2040",
                "name": "\u5b89\u56fd\u5e02",
                "pinyin": "ANGUOSHI"
            }, {
                "city_id": "324",
                "name": "\u5b89\u5eb7\u5e02",
                "pinyin": "ANKANGSHI"
            }, {
                "city_id": "2400",
                "name": "\u5b89\u9646\u5e02",
                "pinyin": "ANLUSHI"
            }, {
                "city_id": "866",
                "name": "\u5b89\u5b81\u5e02",
                "pinyin": "ANNINGSHI"
            }, {
                "city_id": "2641",
                "name": "\u5b89\u5e73\u53bf",
                "pinyin": "ANPINGXIAN"
            }, {
                "city_id": "130",
                "name": "\u5b89\u5e86\u5e02",
                "pinyin": "ANQINGSHI"
            }, {
                "city_id": "1409",
                "name": "\u5b89\u4e18\u5e02",
                "pinyin": "ANQIUSHI"
            }, {
                "city_id": "320",
                "name": "\u978d\u5c71\u5e02",
                "pinyin": "ANSHANSHI"
            }, {
                "city_id": "263",
                "name": "\u5b89\u987a\u5e02",
                "pinyin": "ANSHUNSHI"
            }, {
                "city_id": "1570",
                "name": "\u5b89\u6eaa\u53bf",
                "pinyin": "ANXIXIAN"
            }, {
                "city_id": "267",
                "name": "\u5b89\u9633\u5e02",
                "pinyin": "ANYANGSHI"
            }, {
                "city_id": "51",
                "name": "\u767d\u57ce\u5e02",
                "pinyin": "BAICHENGSHI"
            }, {
                "city_id": "203",
                "name": "\u767e\u8272\u5e02",
                "pinyin": "BAISESHI"
            }, {
                "city_id": "57",
                "name": "\u767d\u5c71\u5e02",
                "pinyin": "BAISHANSHI"
            }, {
                "city_id": "35",
                "name": "\u767d\u94f6\u5e02",
                "pinyin": "BAIYINSHI"
            }, {
                "city_id": "307",
                "name": "\u4fdd\u5b9a\u5e02",
                "pinyin": "BAODINGSHI"
            }, {
                "city_id": "171",
                "name": "\u5b9d\u9e21\u5e02",
                "pinyin": "BAOJISHI"
            }, {
                "city_id": "434",
                "name": "\u5b9d\u6e05\u53bf",
                "pinyin": "BAOQINGXIAN"
            }, {
                "city_id": "112",
                "name": "\u4fdd\u5c71\u5e02",
                "pinyin": "BAOSHANSHI"
            }, {
                "city_id": "229",
                "name": "\u5305\u5934\u5e02",
                "pinyin": "BAOTOUSHI"
            }, {
                "city_id": "1740",
                "name": "\u5b9d\u5e94\u53bf",
                "pinyin": "BAOYINGXIAN"
            }, {
                "city_id": "169",
                "name": "\u5df4\u5f66\u6dd6\u5c14\u5e02",
                "pinyin": "BAYANNAOERSHI"
            }, {
                "city_id": "441",
                "name": "\u5df4\u5f66\u53bf",
                "pinyin": "BAYANXIAN"
            }, {
                "city_id": "86",
                "name": "\u5df4\u97f3\u90ed\u695e\u8499\u53e4\u81ea\u6cbb\u5dde",
                "pinyin": "BAYINGUOLENGMENGGUZIZHIZHOU"
            }, {
                "city_id": "411",
                "name": "\u5317\u5b89\u5e02",
                "pinyin": "BEIANSHI"
            }, {
                "city_id": "295",
                "name": "\u5317\u6d77\u5e02",
                "pinyin": "BEIHAISHI"
            }, {
                "city_id": "1946",
                "name": "\u5317\u9547\u5e02",
                "pinyin": "BEIZHENSHI"
            }, {
                "city_id": "126",
                "name": "\u868c\u57e0\u5e02",
                "pinyin": "BENGBUSHI"
            }, {
                "city_id": "227",
                "name": "\u672c\u6eaa\u5e02",
                "pinyin": "BENXISHI"
            }, {
                "city_id": "206",
                "name": "\u6bd5\u8282\u5730\u533a",
                "pinyin": "BIJIEDIQU"
            }, {
                "city_id": "451",
                "name": "\u5bbe\u53bf",
                "pinyin": "BINXIAN"
            }, {
                "city_id": "235",
                "name": "\u6ee8\u5dde\u5e02",
                "pinyin": "BINZHOUSHI"
            }, {
                "city_id": "88",
                "name": "\u535a\u5c14\u5854\u62c9\u8499\u53e4\u81ea\u6cbb\u5dde",
                "pinyin": "BOERTALAMENGGUZIZHIZHOU"
            }, {
                "city_id": "2642",
                "name": "\u6cca\u5934\u5e02",
                "pinyin": "BOTOUSHI"
            }, {
                "city_id": "188",
                "name": "\u4eb3\u5dde\u5e02",
                "pinyin": "BOZHOUSHI"
            }, {
                "city_id": "149",
                "name": "\u6ca7\u5dde\u5e02",
                "pinyin": "CANGZHOUSHI"
            }, {
                "city_id": "53",
                "name": "\u957f\u6625\u5e02",
                "pinyin": "CHANGCHUNSHI"
            }, {
                "city_id": "219",
                "name": "\u5e38\u5fb7\u5e02",
                "pinyin": "CHANGDESHI"
            }, {
                "city_id": "1541",
                "name": "\u957f\u4e30\u53bf",
                "pinyin": "CHANGFENGXIAN"
            }, {
                "city_id": "1262",
                "name": "\u957f\u845b\u5e02",
                "pinyin": "CHANGGESHI"
            }, {
                "city_id": "93",
                "name": "\u660c\u5409\u56de\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "CHANGJIHUIZUZIZHIZHOU"
            }, {
                "city_id": "1568",
                "name": "\u957f\u4e50\u5e02",
                "pinyin": "CHANGLESHI"
            }, {
                "city_id": "2097",
                "name": "\u5e38\u5b81\u5e02",
                "pinyin": "CHANGNINGSHI"
            }, {
                "city_id": "158",
                "name": "\u957f\u6c99\u5e02",
                "pinyin": "CHANGSHASHI"
            }, {
                "city_id": "2113",
                "name": "\u5e38\u719f\u5e02",
                "pinyin": "CHANGSHUSHI"
            }, {
                "city_id": "2282",
                "name": "\u957f\u5174\u53bf",
                "pinyin": "CHANGXINGXIAN"
            }, {
                "city_id": "356",
                "name": "\u957f\u6cbb\u5e02",
                "pinyin": "CHANGZHISHI"
            }, {
                "city_id": "348",
                "name": "\u5e38\u5dde\u5e02",
                "pinyin": "CHANGZHOUSHI"
            }, {
                "city_id": "251",
                "name": "\u5de2\u6e56\u5e02",
                "pinyin": "CHAOHUSHI"
            }, {
                "city_id": "280",
                "name": "\u671d\u9633\u5e02",
                "pinyin": "CHAOYANGSHI"
            }, {
                "city_id": "201",
                "name": "\u6f6e\u5dde\u5e02",
                "pinyin": "CHAOZHOUSHI"
            }, {
                "city_id": "207",
                "name": "\u627f\u5fb7\u5e02",
                "pinyin": "CHENGDESHI"
            }, {
                "city_id": "75",
                "name": "\u6210\u90fd\u5e02",
                "pinyin": "CHENGDUSHI"
            }, {
                "city_id": "2757",
                "name": "\u6f84\u8fc8\u53bf",
                "pinyin": "CHENGMAIXIAN"
            }, {
                "city_id": "1815",
                "name": "\u6210\u6b66\u53bf",
                "pinyin": "CHENGWUXIAN"
            }, {
                "city_id": "275",
                "name": "\u90f4\u5dde\u5e02",
                "pinyin": "CHENZHOUSHI"
            }, {
                "city_id": "2871",
                "name": "\u8d64\u58c1\u5e02",
                "pinyin": "CHIBISHI"
            }, {
                "city_id": "297",
                "name": "\u8d64\u5cf0\u5e02",
                "pinyin": "CHIFENGSHI"
            }, {
                "city_id": "2170",
                "name": "\u830c\u5e73\u53bf",
                "pinyin": "CHIPINGXIAN"
            }, {
                "city_id": "2854",
                "name": "\u8d64\u6c34\u5e02",
                "pinyin": "CHISHUISHI"
            }, {
                "city_id": "299",
                "name": "\u6c60\u5dde\u5e02",
                "pinyin": "CHIZHOUSHI"
            }, {
                "city_id": "132",
                "name": "\u91cd\u5e86\u5e02",
                "pinyin": "CHONGQINGSHI"
            }, {
                "city_id": "105",
                "name": "\u695a\u96c4\u5f5d\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "CHUXIONGYIZUZIZHIZHOU"
            }, {
                "city_id": "189",
                "name": "\u6ec1\u5dde\u5e02",
                "pinyin": "CHUZHOUSHI"
            }, {
                "city_id": "1879",
                "name": "\u6148\u6eaa\u5e02",
                "pinyin": "CIXISHI"
            }, {
                "city_id": "466",
                "name": "\u5927\u5b89\u5e02",
                "pinyin": "DAANSHI"
            }, {
                "city_id": "167",
                "name": "\u5927\u8fde\u5e02",
                "pinyin": "DALIANSHI"
            }, {
                "city_id": "111",
                "name": "\u5927\u7406\u767d\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "DALIBAIZUZIZHIZHOU"
            }, {
                "city_id": "282",
                "name": "\u4e39\u4e1c\u5e02",
                "pinyin": "DANDONGSHI"
            }, {
                "city_id": "1337",
                "name": "\u4e39\u9633\u5e02",
                "pinyin": "DANYANGSHI"
            }, {
                "city_id": "1215",
                "name": "\u510b\u5dde\u5e02",
                "pinyin": "DANZHOUSHI"
            }, {
                "city_id": "50",
                "name": "\u5927\u5e86\u5e02",
                "pinyin": "DAQINGSHI"
            }, {
                "city_id": "2676",
                "name": "\u5927\u77f3\u6865\u5e02",
                "pinyin": "DASHIQIAOSHI"
            }, {
                "city_id": "355",
                "name": "\u5927\u540c\u5e02",
                "pinyin": "DATONGSHI"
            }, {
                "city_id": "38",
                "name": "\u5927\u5174\u5b89\u5cad\u5730\u533a",
                "pinyin": "DAXINGANLINGDIQU"
            }, {
                "city_id": "1291",
                "name": "\u5927\u51b6\u5e02",
                "pinyin": "DAYESHI"
            }, {
                "city_id": "369",
                "name": "\u8fbe\u5dde\u5e02",
                "pinyin": "DAZHOUSHI"
            }, {
                "city_id": "2134",
                "name": "\u5fb7\u5b89\u53bf",
                "pinyin": "DEANXIAN"
            }, {
                "city_id": "2312",
                "name": "\u5fb7\u5316\u53bf",
                "pinyin": "DEHUAXIAN"
            }, {
                "city_id": "471",
                "name": "\u5fb7\u60e0\u5e02",
                "pinyin": "DEHUISHI"
            }, {
                "city_id": "2076",
                "name": "\u767b\u5c01\u5e02",
                "pinyin": "DENGFENGSHI"
            }, {
                "city_id": "1528",
                "name": "\u706f\u5854\u5e02",
                "pinyin": "DENGTASHI"
            }, {
                "city_id": "74",
                "name": "\u5fb7\u9633\u5e02",
                "pinyin": "DEYANGSHI"
            }, {
                "city_id": "372",
                "name": "\u5fb7\u5dde\u5e02",
                "pinyin": "DEZHOUSHI"
            }, {
                "city_id": "1651",
                "name": "\u5b9a\u5174\u53bf",
                "pinyin": "DINGXINGXIAN"
            }, {
                "city_id": "136",
                "name": "\u5b9a\u897f\u5e02",
                "pinyin": "DINGXISHI"
            }, {
                "city_id": "1232",
                "name": "\u5b9a\u5dde\u5e02",
                "pinyin": "DINGZHOUSHI"
            }, {
                "city_id": "2634",
                "name": "\u4e1c\u65b9\u5e02",
                "pinyin": "DONGFANGSHI"
            }, {
                "city_id": "502",
                "name": "\u4e1c\u4e30\u53bf",
                "pinyin": "DONGFENGXIAN"
            }, {
                "city_id": "1236",
                "name": "\u4e1c\u5149\u53bf",
                "pinyin": "DONGGUANGXIAN"
            }, {
                "city_id": "119",
                "name": "\u4e1c\u839e\u5e02",
                "pinyin": "DONGGUANSHI"
            }, {
                "city_id": "2663",
                "name": "\u4e1c\u6d77\u53bf",
                "pinyin": "DONGHAIXIAN"
            }, {
                "city_id": "503",
                "name": "\u4e1c\u8fbd\u53bf",
                "pinyin": "DONGLIAOXIAN"
            }, {
                "city_id": "2160",
                "name": "\u4e1c\u660e\u53bf",
                "pinyin": "DONGMINGXIAN"
            }, {
                "city_id": "1578",
                "name": "\u4e1c\u5c71\u53bf",
                "pinyin": "DONGSHANXIAN"
            }, {
                "city_id": "120",
                "name": "\u4e1c\u6c99\u7fa4\u5c9b",
                "pinyin": "DONGSHAQUNDAO"
            }, {
                "city_id": "1739",
                "name": "\u4e1c\u53f0\u5e02",
                "pinyin": "DONGTAISHI"
            }, {
                "city_id": "1195",
                "name": "\u4e1c\u5174\u5e02",
                "pinyin": "DONGXINGSHI"
            }, {
                "city_id": "1472",
                "name": "\u4e1c\u9633\u5e02",
                "pinyin": "DONGYANGSHI"
            }, {
                "city_id": "174",
                "name": "\u4e1c\u8425\u5e02",
                "pinyin": "DONGYINGSHI"
            }, {
                "city_id": "476",
                "name": "\u6566\u5316\u5e02",
                "pinyin": "DUNHUASHI"
            }, {
                "city_id": "1010",
                "name": "\u591a\u4f26\u53bf",
                "pinyin": "DUOLUNXIAN"
            }, {
                "city_id": "283",
                "name": "\u9102\u5c14\u591a\u65af\u5e02",
                "pinyin": "EERDUOSISHI"
            }, {
                "city_id": "373",
                "name": "\u6069\u65bd\u571f\u5bb6\u65cf\u82d7\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "ENSHITUJIAZUMIAOZUZIZHIZHOU"
            }, {
                "city_id": "559",
                "name": "\u4e8c\u8fde\u6d69\u7279\u5e02",
                "pinyin": "ERLIANHAOTESHI"
            }, {
                "city_id": "122",
                "name": "\u9102\u5dde\u5e02",
                "pinyin": "EZHOUSHI"
            }
        ],
        "FGHIJ": [
            {
                "city_id": "1542",
                "name": "\u7e41\u660c\u53bf",
                "pinyin": "FANCHANGXIAN"
            }, {
                "city_id": "204",
                "name": "\u9632\u57ce\u6e2f\u5e02",
                "pinyin": "FANGCHENGGANGSHI"
            }, {
                "city_id": "2823",
                "name": "\u80a5\u57ce\u5e02",
                "pinyin": "FEICHENGSHI"
            }, {
                "city_id": "1950",
                "name": "\u80a5\u4e1c\u53bf",
                "pinyin": "FEIDONGXIAN"
            }, {
                "city_id": "2298",
                "name": "\u80a5\u897f\u53bf",
                "pinyin": "FEIXIXIAN"
            }, {
                "city_id": "1769",
                "name": "\u4e30\u57ce\u5e02",
                "pinyin": "FENGCHENGSHI"
            }, {
                "city_id": "2833",
                "name": "\u5949\u5316\u5e02",
                "pinyin": "FENGHUASHI"
            }, {
                "city_id": "1331",
                "name": "\u4e30\u53bf",
                "pinyin": "FENGXIAN"
            }, {
                "city_id": "1766",
                "name": "\u5949\u65b0\u53bf",
                "pinyin": "FENGXINXIAN"
            }, {
                "city_id": "7967",
                "name": "\u4e30\u6cfd\u533a",
                "pinyin": "FENGZEQU"
            }, {
                "city_id": "2471",
                "name": "\u6c7e\u9633\u5e02",
                "pinyin": "FENYANGSHI"
            }, {
                "city_id": "138",
                "name": "\u4f5b\u5c71\u5e02",
                "pinyin": "FOSHANSHI"
            }, {
                "city_id": "2317",
                "name": "\u798f\u6e05\u5e02",
                "pinyin": "FUQINGSHI"
            }, {
                "city_id": "184",
                "name": "\u629a\u987a\u5e02",
                "pinyin": "FUSHUNSHI"
            }, {
                "city_id": "59",
                "name": "\u961c\u65b0\u5e02",
                "pinyin": "FUXINSHI"
            }, {
                "city_id": "128",
                "name": "\u961c\u9633\u5e02",
                "pinyin": "FUYANGSHI"
            }, {
                "city_id": "2216",
                "name": "\u5bcc\u9633\u5e02",
                "pinyin": "FUYANGSHI"
            }, {
                "city_id": "470",
                "name": "\u6276\u4f59\u53bf",
                "pinyin": "FUYUXIAN"
            }, {
                "city_id": "226",
                "name": "\u629a\u5dde\u5e02",
                "pinyin": "FUZHOUSHI"
            }, {
                "city_id": "300",
                "name": "\u798f\u5dde\u5e02",
                "pinyin": "FUZHOUSHI"
            }, {
                "city_id": "247",
                "name": "\u7518\u5357\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "GANNANZANGZUZIZHIZHOU"
            }, {
                "city_id": "365",
                "name": "\u8d63\u5dde\u5e02",
                "pinyin": "GANZHOUSHI"
            }, {
                "city_id": "2039",
                "name": "\u9ad8\u9633\u53bf",
                "pinyin": "GAOYANGXIAN"
            }, {
                "city_id": "1239",
                "name": "\u9ad8\u9091\u53bf",
                "pinyin": "GAOYIXIAN"
            }, {
                "city_id": "2117",
                "name": "\u9ad8\u90ae\u5e02",
                "pinyin": "GAOYOUSHI"
            }, {
                "city_id": "1681",
                "name": "\u5de9\u4e49\u5e02",
                "pinyin": "GONGYISHI"
            }, {
                "city_id": "484",
                "name": "\u516c\u4e3b\u5cad\u5e02",
                "pinyin": "GONGZHULINGSHI"
            }, {
                "city_id": "241",
                "name": "\u5e7f\u5b89\u5e02",
                "pinyin": "GUANGANSHI"
            }, {
                "city_id": "1504",
                "name": "\u5e7f\u6c34\u5e02",
                "pinyin": "GUANGSHUISHI"
            }, {
                "city_id": "329",
                "name": "\u5e7f\u5143\u5e02",
                "pinyin": "GUANGYUANSHI"
            }, {
                "city_id": "1744",
                "name": "\u704c\u5357\u53bf",
                "pinyin": "GUANNANXIAN"
            }, {
                "city_id": "1925",
                "name": "\u51a0\u53bf",
                "pinyin": "GUANXIAN"
            }, {
                "city_id": "2112",
                "name": "\u704c\u4e91\u53bf",
                "pinyin": "GUANYUNXIAN"
            }, {
                "city_id": "1921",
                "name": "\u6545\u57ce\u53bf",
                "pinyin": "GUCHENGXIAN"
            }, {
                "city_id": "341",
                "name": "\u8d35\u6e2f\u5e02",
                "pinyin": "GUIGANGSHI"
            }, {
                "city_id": "142",
                "name": "\u6842\u6797\u5e02",
                "pinyin": "GUILINSHI"
            }, {
                "city_id": "2742",
                "name": "\u8d35\u6eaa\u5e02",
                "pinyin": "GUIXISHI"
            }, {
                "city_id": "146",
                "name": "\u8d35\u9633\u5e02",
                "pinyin": "GUIYANGSHI"
            }, {
                "city_id": "72",
                "name": "\u679c\u6d1b\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "GUOLUOZANGZUZIZHIZHOU"
            }, {
                "city_id": "246",
                "name": "\u56fa\u539f\u5e02",
                "pinyin": "GUYUANSHI"
            }, {
                "city_id": "399",
                "name": "\u6cbd\u6e90\u53bf",
                "pinyin": "GUYUANXIAN"
            }, {
                "city_id": "48",
                "name": "\u54c8\u5c14\u6ee8\u5e02",
                "pinyin": "HAERBINSHI"
            }, {
                "city_id": "67",
                "name": "\u6d77\u5317\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "HAIBEIZANGZUZIZHIZHOU"
            }, {
                "city_id": "2136",
                "name": "\u6d77\u57ce\u5e02",
                "pinyin": "HAICHENGSHI"
            }, {
                "city_id": "69",
                "name": "\u6d77\u4e1c\u5730\u533a",
                "pinyin": "HAIDONGDIQU"
            }, {
                "city_id": "2002",
                "name": "\u6d77\u4e30\u53bf",
                "pinyin": "HAIFENGXIAN"
            }, {
                "city_id": "125",
                "name": "\u6d77\u53e3\u5e02",
                "pinyin": "HAIKOUSHI"
            }, {
                "city_id": "1030",
                "name": "\u6d77\u6797\u5e02",
                "pinyin": "HAILINSHI"
            }, {
                "city_id": "422",
                "name": "\u6d77\u4f26\u5e02",
                "pinyin": "HAILUNSHI"
            }, {
                "city_id": "68",
                "name": "\u6d77\u5357\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "HAINANZANGZUZIZHIZHOU"
            }, {
                "city_id": "2834",
                "name": "\u6d77\u5b81\u5e02",
                "pinyin": "HAININGSHI"
            }, {
                "city_id": "65",
                "name": "\u6d77\u897f\u8499\u53e4\u65cf\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "HAIXIMENGGUZUZANGZUZIZHIZHOU"
            }, {
                "city_id": "91",
                "name": "\u54c8\u5bc6\u5730\u533a",
                "pinyin": "HAMIDIQU"
            }, {
                "city_id": "151",
                "name": "\u90af\u90f8\u5e02",
                "pinyin": "HANDANSHI"
            }, {
                "city_id": "179",
                "name": "\u676d\u5dde\u5e02",
                "pinyin": "HANGZHOUSHI"
            }, {
                "city_id": "1103",
                "name": "\u542b\u5c71\u53bf",
                "pinyin": "HANSHANXIAN"
            }, {
                "city_id": "352",
                "name": "\u6c49\u4e2d\u5e02",
                "pinyin": "HANZHONGSHI"
            }, {
                "city_id": "215",
                "name": "\u9e64\u58c1\u5e02",
                "pinyin": "HEBISHI"
            }, {
                "city_id": "143",
                "name": "\u6cb3\u6c60\u5e02",
                "pinyin": "HECHISHI"
            }, {
                "city_id": "127",
                "name": "\u5408\u80a5\u5e02",
                "pinyin": "HEFEISHI"
            }, {
                "city_id": "43",
                "name": "\u9e64\u5c97\u5e02",
                "pinyin": "HEGANGSHI"
            }, {
                "city_id": "39",
                "name": "\u9ed1\u6cb3\u5e02",
                "pinyin": "HEIHESHI"
            }, {
                "city_id": "523",
                "name": "\u9ed1\u5c71\u53bf",
                "pinyin": "HEISHANXIAN"
            }, {
                "city_id": "1652",
                "name": "\u6cb3\u95f4\u5e02",
                "pinyin": "HEJIANSHI"
            }, {
                "city_id": "2891",
                "name": "\u6cb3\u6d25\u5e02",
                "pinyin": "HEJINSHI"
            }, {
                "city_id": "208",
                "name": "\u8861\u6c34\u5e02",
                "pinyin": "HENGSHUISHI"
            }, {
                "city_id": "159",
                "name": "\u8861\u9633\u5e02",
                "pinyin": "HENGYANGSHI"
            }, {
                "city_id": "82",
                "name": "\u548c\u7530\u5730\u533a",
                "pinyin": "HETIANDIQU"
            }, {
                "city_id": "200",
                "name": "\u6cb3\u6e90\u5e02",
                "pinyin": "HEYUANSHI"
            }, {
                "city_id": "353",
                "name": "\u83cf\u6cfd\u5e02",
                "pinyin": "HEZESHI"
            }, {
                "city_id": "260",
                "name": "\u8d3a\u5dde\u5e02",
                "pinyin": "HEZHOUSHI"
            }, {
                "city_id": "487",
                "name": "\u6866\u7538\u5e02",
                "pinyin": "HUADIANSHI"
            }, {
                "city_id": "162",
                "name": "\u6dee\u5b89\u5e02",
                "pinyin": "HUAIANSHI"
            }, {
                "city_id": "253",
                "name": "\u6dee\u5317\u5e02",
                "pinyin": "HUAIBEISHI"
            }, {
                "city_id": "363",
                "name": "\u6000\u5316\u5e02",
                "pinyin": "HUAIHUASHI"
            }, {
                "city_id": "250",
                "name": "\u6dee\u5357\u5e02",
                "pinyin": "HUAINANSHI"
            }, {
                "city_id": "437",
                "name": "\u6866\u5357\u53bf",
                "pinyin": "HUANANXIAN"
            }, {
                "city_id": "271",
                "name": "\u9ec4\u5188\u5e02",
                "pinyin": "HUANGGANGSHI"
            }, {
                "city_id": "2262",
                "name": "\u9ec4\u9a85\u5e02",
                "pinyin": "HUANGHUASHI"
            }, {
                "city_id": "70",
                "name": "\u9ec4\u5357\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "HUANGNANZANGZUZIZHIZHOU"
            }, {
                "city_id": "252",
                "name": "\u9ec4\u5c71\u5e02",
                "pinyin": "HUANGSHANSHI"
            }, {
                "city_id": "311",
                "name": "\u9ec4\u77f3\u5e02",
                "pinyin": "HUANGSHISHI"
            }, {
                "city_id": "321",
                "name": "\u547c\u548c\u6d69\u7279\u5e02",
                "pinyin": "HUHEHAOTESHI"
            }, {
                "city_id": "500",
                "name": "\u8f89\u5357\u53bf",
                "pinyin": "HUINANXIAN"
            }, {
                "city_id": "301",
                "name": "\u60e0\u5dde\u5e02",
                "pinyin": "HUIZHOUSHI"
            }, {
                "city_id": "319",
                "name": "\u846b\u82a6\u5c9b\u5e02",
                "pinyin": "HULUDAOSHI"
            }, {
                "city_id": "61",
                "name": "\u547c\u4f26\u8d1d\u5c14\u5e02",
                "pinyin": "HULUNBEIERSHI"
            }, {
                "city_id": "509",
                "name": "\u73f2\u6625\u5e02",
                "pinyin": "HUNCHUNSHI"
            }, {
                "city_id": "2498",
                "name": "\u970d\u90b1\u53bf",
                "pinyin": "HUOQIUXIAN"
            }, {
                "city_id": "294",
                "name": "\u6e56\u5dde\u5e02",
                "pinyin": "HUZHOUSHI"
            }, {
                "city_id": "42",
                "name": "\u4f73\u6728\u65af\u5e02",
                "pinyin": "JIAMUSISHI"
            }, {
                "city_id": "2828",
                "name": "\u5efa\u5fb7\u5e02",
                "pinyin": "JIANDESHI"
            }, {
                "city_id": "1133",
                "name": "\u5c06\u4e50\u53bf",
                "pinyin": "JIANGLEXIAN"
            }, {
                "city_id": "302",
                "name": "\u6c5f\u95e8\u5e02",
                "pinyin": "JIANGMENSHI"
            }, {
                "city_id": "1873",
                "name": "\u6c5f\u5c71\u5e02",
                "pinyin": "JIANGSHANSHI"
            }, {
                "city_id": "2819",
                "name": "\u6c5f\u9634\u5e02",
                "pinyin": "JIANGYINSHI"
            }, {
                "city_id": "2310",
                "name": "\u5efa\u74ef\u5e02",
                "pinyin": "JIANOUSHI"
            }, {
                "city_id": "318",
                "name": "\u5409\u5b89\u5e02",
                "pinyin": "JIANSHI"
            }, {
                "city_id": "883",
                "name": "\u5efa\u6c34\u53bf",
                "pinyin": "JIANSHUIXIAN"
            }, {
                "city_id": "478",
                "name": "\u86df\u6cb3\u5e02",
                "pinyin": "JIAOHESHI"
            }, {
                "city_id": "2691",
                "name": "\u80f6\u5dde\u5e02",
                "pinyin": "JIAOZHOUSHI"
            }, {
                "city_id": "211",
                "name": "\u7126\u4f5c\u5e02",
                "pinyin": "JIAOZUOSHI"
            }, {
                "city_id": "1760",
                "name": "\u8d3e\u6c6a\u533a",
                "pinyin": "JIAWANGQU"
            }, {
                "city_id": "1402",
                "name": "\u5609\u7965\u53bf",
                "pinyin": "JIAXIANGXIAN"
            }, {
                "city_id": "334",
                "name": "\u5609\u5174\u5e02",
                "pinyin": "JIAXINGSHI"
            }, {
                "city_id": "33",
                "name": "\u5609\u5cea\u5173\u5e02",
                "pinyin": "JIAYUGUANSHI"
            }, {
                "city_id": "259",
                "name": "\u63ed\u9633\u5e02",
                "pinyin": "JIEYANGSHI"
            }, {
                "city_id": "55",
                "name": "\u5409\u6797\u5e02",
                "pinyin": "JILINSHI"
            }, {
                "city_id": "2181",
                "name": "\u5373\u58a8\u5e02",
                "pinyin": "JIMOSHI"
            }, {
                "city_id": "288",
                "name": "\u6d4e\u5357\u5e02",
                "pinyin": "JINANSHI"
            }, {
                "city_id": "34",
                "name": "\u91d1\u660c\u5e02",
                "pinyin": "JINCHANGSHI"
            }, {
                "city_id": "290",
                "name": "\u664b\u57ce\u5e02",
                "pinyin": "JINCHENGSHI"
            }, {
                "city_id": "225",
                "name": "\u666f\u5fb7\u9547\u5e02",
                "pinyin": "JINGDEZHENSHI"
            }, {
                "city_id": "901",
                "name": "\u666f\u6d2a\u5e02",
                "pinyin": "JINGHONGSHI"
            }, {
                "city_id": "1333",
                "name": "\u9756\u6c5f\u5e02",
                "pinyin": "JINGJIANGSHI"
            }, {
                "city_id": "217",
                "name": "\u8346\u95e8\u5e02",
                "pinyin": "JINGMENSHI"
            }, {
                "city_id": "2558",
                "name": "\u666f\u53bf",
                "pinyin": "JINGXIAN"
            }, {
                "city_id": "157",
                "name": "\u8346\u5dde\u5e02",
                "pinyin": "JINGZHOUSHI"
            }, {
                "city_id": "333",
                "name": "\u91d1\u534e\u5e02",
                "pinyin": "JINHUASHI"
            }, {
                "city_id": "2667",
                "name": "\u91d1\u6e56\u53bf",
                "pinyin": "JINHUXIAN"
            }, {
                "city_id": "286",
                "name": "\u6d4e\u5b81\u5e02",
                "pinyin": "JININGSHI"
            }, {
                "city_id": "1144",
                "name": "\u664b\u6c5f\u5e02",
                "pinyin": "JINJIANGSHI"
            }, {
                "city_id": "2118",
                "name": "\u91d1\u575b\u5e02",
                "pinyin": "JINTANSHI"
            }, {
                "city_id": "2880",
                "name": "\u91d1\u4e61\u53bf",
                "pinyin": "JINXIANGXIAN"
            }, {
                "city_id": "238",
                "name": "\u664b\u4e2d\u5e02",
                "pinyin": "JINZHONGSHI"
            }, {
                "city_id": "166",
                "name": "\u9526\u5dde\u5e02",
                "pinyin": "JINZHOUSHI"
            }, {
                "city_id": "1317",
                "name": "\u5409\u9996\u5e02",
                "pinyin": "JISHOUSHI"
            }, {
                "city_id": "349",
                "name": "\u4e5d\u6c5f\u5e02",
                "pinyin": "JIUJIANGSHI"
            }, {
                "city_id": "37",
                "name": "\u9152\u6cc9\u5e02",
                "pinyin": "JIUQUANSHI"
            }, {
                "city_id": "479",
                "name": "\u4e5d\u53f0\u5e02",
                "pinyin": "JIUTAISHI"
            }, {
                "city_id": "46",
                "name": "\u9e21\u897f\u5e02",
                "pinyin": "JIXISHI"
            }, {
                "city_id": "1827",
                "name": "\u6d4e\u9633\u53bf",
                "pinyin": "JIYANGXIAN"
            }, {
                "city_id": "1277",
                "name": "\u6d4e\u6e90\u5e02",
                "pinyin": "JIYUANSHI"
            }, {
                "city_id": "2046",
                "name": "\u5180\u5dde\u5e02",
                "pinyin": "JIZHOUSHI"
            }, {
                "city_id": "2582",
                "name": "\u8392\u5357\u53bf",
                "pinyin": "JUNANXIAN"
            }, {
                "city_id": "1322",
                "name": "\u53e5\u5bb9\u5e02",
                "pinyin": "JURONGSHI"
            }, {
                "city_id": "1817",
                "name": "\u8392\u53bf",
                "pinyin": "JUXIAN"
            }, {
                "city_id": "2452",
                "name": "\u5de8\u91ce\u53bf",
                "pinyin": "JUYEXIAN"
            }
        ],
        "KLMNO": [
            {
                "city_id": "210",
                "name": "\u5f00\u5c01\u5e02",
                "pinyin": "KAIFENGSHI"
            }, {
                "city_id": "2025",
                "name": "\u51ef\u91cc\u5e02",
                "pinyin": "KAILISHI"
            }, {
                "city_id": "1046",
                "name": "\u5f00\u539f\u5e02",
                "pinyin": "KAIYUANSHI"
            }, {
                "city_id": "83",
                "name": "\u5580\u4ec0\u5730\u533a",
                "pinyin": "KASHIDIQU"
            }, {
                "city_id": "95",
                "name": "\u514b\u62c9\u739b\u4f9d\u5e02",
                "pinyin": "KELAMAYISHI"
            }, {
                "city_id": "1414",
                "name": "\u57a6\u5229\u53bf",
                "pinyin": "KENLIXIAN"
            }, {
                "city_id": "84",
                "name": "\u514b\u5b5c\u52d2\u82cf\u67ef\u5c14\u514b\u5b5c\u81ea\u6cbb\u5dde",
                "pinyin": "KEZILESUKEERKEZIZIZHIZHOU"
            }, {
                "city_id": "104",
                "name": "\u6606\u660e\u5e02",
                "pinyin": "KUNMINGSHI"
            }, {
                "city_id": "2581",
                "name": "\u6606\u5c71\u5e02",
                "pinyin": "KUNSHANSHI"
            }, {
                "city_id": "202",
                "name": "\u6765\u5bbe\u5e02",
                "pinyin": "LAIBINSHI"
            }, {
                "city_id": "124",
                "name": "\u83b1\u829c\u5e02",
                "pinyin": "LAIWUSHI"
            }, {
                "city_id": "2180",
                "name": "\u83b1\u5dde\u5e02",
                "pinyin": "LAIZHOUSHI"
            }, {
                "city_id": "191",
                "name": "\u5eca\u574a\u5e02",
                "pinyin": "LANGFANGSHI"
            }, {
                "city_id": "1462",
                "name": "\u5170\u6eaa\u5e02",
                "pinyin": "LANXISHI"
            }, {
                "city_id": "36",
                "name": "\u5170\u5dde\u5e02",
                "pinyin": "LANZHOUSHI"
            }, {
                "city_id": "1225",
                "name": "\u4e50\u4ead\u53bf",
                "pinyin": "LAOTINGXIAN"
            }, {
                "city_id": "100",
                "name": "\u62c9\u8428\u5e02",
                "pinyin": "LASASHI"
            }, {
                "city_id": "1308",
                "name": "\u8012\u9633\u5e02",
                "pinyin": "LEIYANGSHI"
            }, {
                "city_id": "79",
                "name": "\u4e50\u5c71\u5e02",
                "pinyin": "LESHANSHI"
            }, {
                "city_id": "80",
                "name": "\u51c9\u5c71\u5f5d\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "LIANGSHANYIZUZIZHIZHOU"
            }, {
                "city_id": "1135",
                "name": "\u8fde\u6c5f\u53bf",
                "pinyin": "LIANJIANGXIAN"
            }, {
                "city_id": "2419",
                "name": "\u6d9f\u6c34\u53bf",
                "pinyin": "LIANSHUIXIAN"
            }, {
                "city_id": "347",
                "name": "\u8fde\u4e91\u6e2f\u5e02",
                "pinyin": "LIANYUNGANGSHI"
            }, {
                "city_id": "366",
                "name": "\u804a\u57ce\u5e02",
                "pinyin": "LIAOCHENGSHI"
            }, {
                "city_id": "351",
                "name": "\u8fbd\u9633\u5e02",
                "pinyin": "LIAOYANGSHI"
            }, {
                "city_id": "2882",
                "name": "\u8fbd\u9633\u53bf",
                "pinyin": "LIAOYANGXIAN"
            }, {
                "city_id": "183",
                "name": "\u8fbd\u6e90\u5e02",
                "pinyin": "LIAOYUANSHI"
            }, {
                "city_id": "1529",
                "name": "\u8fbd\u4e2d\u53bf",
                "pinyin": "LIAOZHONGXIAN"
            }, {
                "city_id": "7966",
                "name": "\u9ca4\u57ce\u533a",
                "pinyin": "LICHENGQU"
            }, {
                "city_id": "2725",
                "name": "\u5229\u5ddd\u5e02",
                "pinyin": "LICHUANSHI"
            }, {
                "city_id": "114",
                "name": "\u4e3d\u6c5f\u5e02",
                "pinyin": "LIJIANGSHI"
            }, {
                "city_id": "1878",
                "name": "\u4e34\u5b89\u5e02",
                "pinyin": "LINANSHI"
            }, {
                "city_id": "110",
                "name": "\u4e34\u6ca7\u5e02",
                "pinyin": "LINCANGSHI"
            }, {
                "city_id": "368",
                "name": "\u4e34\u6c7e\u5e02",
                "pinyin": "LINFENSHI"
            }, {
                "city_id": "1364",
                "name": "\u51cc\u6d77\u5e02",
                "pinyin": "LINGHAISHI"
            }, {
                "city_id": "1643",
                "name": "\u9675\u6c34\u9ece\u65cf\u81ea\u6cbb\u53bf",
                "pinyin": "LINGSHUILIZUZIZHIXIAN"
            }, {
                "city_id": "1460",
                "name": "\u4e34\u6d77\u5e02",
                "pinyin": "LINHAISHI"
            }, {
                "city_id": "2837",
                "name": "\u4e34\u6cc9\u53bf",
                "pinyin": "LINQUANXIAN"
            }, {
                "city_id": "1823",
                "name": "\u4e34\u6710\u53bf",
                "pinyin": "LINQUXIAN"
            }, {
                "city_id": "182",
                "name": "\u4e34\u590f\u56de\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "LINXIAHUIZUZIZHIZHOU"
            }, {
                "city_id": "234",
                "name": "\u4e34\u6c82\u5e02",
                "pinyin": "LINYISHI"
            }, {
                "city_id": "292",
                "name": "\u4e3d\u6c34\u5e02",
                "pinyin": "LISHUISHI"
            }, {
                "city_id": "2116",
                "name": "\u6ea7\u6c34\u53bf",
                "pinyin": "LISHUIXIAN"
            }, {
                "city_id": "147",
                "name": "\u516d\u76d8\u6c34\u5e02",
                "pinyin": "LIUPANSHUISHI"
            }, {
                "city_id": "2577",
                "name": "\u6d4f\u9633\u5e02",
                "pinyin": "LIUYANGSHI"
            }, {
                "city_id": "305",
                "name": "\u67f3\u5dde\u5e02",
                "pinyin": "LIUZHOUSHI"
            }, {
                "city_id": "1231",
                "name": "\u8821\u53bf",
                "pinyin": "LIXIAN"
            }, {
                "city_id": "1747",
                "name": "\u6ea7\u9633\u5e02",
                "pinyin": "LIYANGSHI"
            }, {
                "city_id": "432",
                "name": "\u9f99\u6c5f\u53bf",
                "pinyin": "LONGJIANGXIAN"
            }, {
                "city_id": "256",
                "name": "\u9647\u5357\u5e02",
                "pinyin": "LONGNANSHI"
            }, {
                "city_id": "193",
                "name": "\u9f99\u5ca9\u5e02",
                "pinyin": "LONGYANSHI"
            }, {
                "city_id": "221",
                "name": "\u5a04\u5e95\u5e02",
                "pinyin": "LOUDISHI"
            }, {
                "city_id": "298",
                "name": "\u516d\u5b89\u5e02",
                "pinyin": "LUANSHI"
            }, {
                "city_id": "1173",
                "name": "\u9646\u4e30\u5e02",
                "pinyin": "LUFENGSHI"
            }, {
                "city_id": "1107",
                "name": "\u5e90\u6c5f\u53bf",
                "pinyin": "LUJIANGXIAN"
            }, {
                "city_id": "327",
                "name": "\u5415\u6881\u5e02",
                "pinyin": "LULIANGSHI"
            }, {
                "city_id": "344",
                "name": "\u6f2f\u6cb3\u5e02",
                "pinyin": "LUOHESHI"
            }, {
                "city_id": "7963",
                "name": "\u6d1b\u6c5f\u533a",
                "pinyin": "LUOJIANGQU"
            }, {
                "city_id": "153",
                "name": "\u6d1b\u9633\u5e02",
                "pinyin": "LUOYANGSHI"
            }, {
                "city_id": "331",
                "name": "\u6cf8\u5dde\u5e02",
                "pinyin": "LUZHOUSHI"
            }, {
                "city_id": "358",
                "name": "\u9a6c\u978d\u5c71\u5e02",
                "pinyin": "MAANSHANSHI"
            }, {
                "city_id": "2504",
                "name": "\u9ebb\u57ce\u5e02",
                "pinyin": "MACHENGSHI"
            }, {
                "city_id": "1228",
                "name": "\u6ee1\u57ce\u53bf",
                "pinyin": "MANCHENGXIAN"
            }, {
                "city_id": "139",
                "name": "\u8302\u540d\u5e02",
                "pinyin": "MAOMINGSHI"
            }, {
                "city_id": "501",
                "name": "\u6885\u6cb3\u53e3\u5e02",
                "pinyin": "MEIHEKOUSHI"
            }, {
                "city_id": "77",
                "name": "\u7709\u5c71\u5e02",
                "pinyin": "MEISHANSHI"
            }, {
                "city_id": "141",
                "name": "\u6885\u5dde\u5e02",
                "pinyin": "MEIZHOUSHI"
            }, {
                "city_id": "1100",
                "name": "\u8499\u57ce\u53bf",
                "pinyin": "MENGCHENGXIAN"
            }, {
                "city_id": "894",
                "name": "\u8499\u81ea\u53bf",
                "pinyin": "MENGZIXIAN"
            }, {
                "city_id": "240",
                "name": "\u7ef5\u9633\u5e02",
                "pinyin": "MIANYANGSHI"
            }, {
                "city_id": "964",
                "name": "\u6c11\u4e50\u53bf",
                "pinyin": "MINYUEXIAN"
            }, {
                "city_id": "49",
                "name": "\u7261\u4e39\u6c5f\u5e02",
                "pinyin": "MUDANJIANGSHI"
            }, {
                "city_id": "440",
                "name": "\u6728\u5170\u53bf",
                "pinyin": "MULANXIAN"
            }, {
                "city_id": "163",
                "name": "\u5357\u660c\u5e02",
                "pinyin": "NANCHANGSHI"
            }, {
                "city_id": "291",
                "name": "\u5357\u5145\u5e02",
                "pinyin": "NANCHONGSHI"
            }, {
                "city_id": "2638",
                "name": "\u5357\u5bab\u5e02",
                "pinyin": "NANGONGSHI"
            }, {
                "city_id": "1244",
                "name": "\u5357\u548c\u53bf",
                "pinyin": "NANHEXIAN"
            }, {
                "city_id": "315",
                "name": "\u5357\u4eac\u5e02",
                "pinyin": "NANJINGSHI"
            }, {
                "city_id": "261",
                "name": "\u5357\u5b81\u5e02",
                "pinyin": "NANNINGSHI"
            }, {
                "city_id": "133",
                "name": "\u5357\u5e73\u5e02",
                "pinyin": "NANPINGSHI"
            }, {
                "city_id": "1515",
                "name": "\u5357\u6c99\u7fa4\u5c9b",
                "pinyin": "NANSHAQUNDAO"
            }, {
                "city_id": "161",
                "name": "\u5357\u901a\u5e02",
                "pinyin": "NANTONGSHI"
            }, {
                "city_id": "309",
                "name": "\u5357\u9633\u5e02",
                "pinyin": "NANYANGSHI"
            }, {
                "city_id": "410",
                "name": "\u8bb7\u6cb3\u5e02",
                "pinyin": "NEHESHI"
            }, {
                "city_id": "248",
                "name": "\u5185\u6c5f\u5e02",
                "pinyin": "NEIJIANGSHI"
            }, {
                "city_id": "1240",
                "name": "\u5185\u90b1\u53bf",
                "pinyin": "NEIQIUXIAN"
            }, {
                "city_id": "404",
                "name": "\u5ae9\u6c5f\u53bf",
                "pinyin": "NENJIANGXIAN"
            }, {
                "city_id": "180",
                "name": "\u5b81\u6ce2\u5e02",
                "pinyin": "NINGBOSHI"
            }, {
                "city_id": "192",
                "name": "\u5b81\u5fb7\u5e02",
                "pinyin": "NINGDESHI"
            }, {
                "city_id": "1463",
                "name": "\u5b81\u6d77\u53bf",
                "pinyin": "NINGHAIXIAN"
            }, {
                "city_id": "1238",
                "name": "\u5b81\u664b\u53bf",
                "pinyin": "NINGJINXIAN"
            }, {
                "city_id": "1406",
                "name": "\u5b81\u9633\u53bf",
                "pinyin": "NINGYANGXIAN"
            }, {
                "city_id": "472",
                "name": "\u519c\u5b89\u53bf",
                "pinyin": "NONGANXIAN"
            }
        ],
        "PQRST": [
            {
                "city_id": "228",
                "name": "\u76d8\u9526\u5e02",
                "pinyin": "PANJINSHI"
            }, {
                "city_id": "489",
                "name": "\u78d0\u77f3\u5e02",
                "pinyin": "PANSHISHI"
            }, {
                "city_id": "81",
                "name": "\u6500\u679d\u82b1\u5e02",
                "pinyin": "PANZHIHUASHI"
            }, {
                "city_id": "1746",
                "name": "\u6c9b\u53bf",
                "pinyin": "PEIXIAN"
            }, {
                "city_id": "617",
                "name": "\u5f6d\u5dde\u5e02",
                "pinyin": "PENGZHOUSHI"
            }, {
                "city_id": "1210",
                "name": "\u5e73\u575d\u53bf",
                "pinyin": "PINGBAXIAN"
            }, {
                "city_id": "213",
                "name": "\u5e73\u9876\u5c71\u5e02",
                "pinyin": "PINGDINGSHANSHI"
            }, {
                "city_id": "2528",
                "name": "\u5e73\u548c\u53bf",
                "pinyin": "PINGHEXIAN"
            }, {
                "city_id": "2801",
                "name": "\u5e73\u6e56\u5e02",
                "pinyin": "PINGHUSHI"
            }, {
                "city_id": "359",
                "name": "\u5e73\u51c9\u5e02",
                "pinyin": "PINGLIANGSHI"
            }, {
                "city_id": "350",
                "name": "\u840d\u4e61\u5e02",
                "pinyin": "PINGXIANGSHI"
            }, {
                "city_id": "1666",
                "name": "\u5e73\u4e61\u53bf",
                "pinyin": "PINGXIANGXIAN"
            }, {
                "city_id": "2705",
                "name": "\u5e73\u9633\u53bf",
                "pinyin": "PINGYANGXIAN"
            }, {
                "city_id": "2172",
                "name": "\u5e73\u539f\u53bf",
                "pinyin": "PINGYUANXIAN"
            }, {
                "city_id": "2647",
                "name": "\u5e73\u8206\u53bf",
                "pinyin": "PINGYUXIAN"
            }, {
                "city_id": "1329",
                "name": "\u90b3\u5dde\u5e02",
                "pinyin": "PIZHOUSHI"
            }, {
                "city_id": "2525",
                "name": "\u6d66\u57ce\u53bf",
                "pinyin": "PUCHENGXIAN"
            }, {
                "city_id": "108",
                "name": "\u666e\u6d31\u5e02",
                "pinyin": "PUERSHI"
            }, {
                "city_id": "195",
                "name": "\u8386\u7530\u5e02",
                "pinyin": "PUTIANSHI"
            }, {
                "city_id": "209",
                "name": "\u6fee\u9633\u5e02",
                "pinyin": "PUYANGSHI"
            }, {
                "city_id": "1223",
                "name": "\u8fc1\u5b89\u5e02",
                "pinyin": "QIANANSHI"
            }, {
                "city_id": "342",
                "name": "\u9ed4\u4e1c\u5357\u82d7\u65cf\u4f97\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "QIANDONGNANMIAOZUDONGZUZIZHIZHOU"
            }, {
                "city_id": "1293",
                "name": "\u6f5c\u6c5f\u5e02",
                "pinyin": "QIANJIANGSHI"
            }, {
                "city_id": "306",
                "name": "\u9ed4\u5357\u5e03\u4f9d\u65cf\u82d7\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "QIANNANBUYIZUMIAOZUZIZHIZHOU"
            }, {
                "city_id": "651",
                "name": "\u728d\u4e3a\u53bf",
                "pinyin": "QIANWEIXIAN"
            }, {
                "city_id": "343",
                "name": "\u9ed4\u897f\u5357\u5e03\u4f9d\u65cf\u82d7\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "QIANXINANBUYIZUMIAOZUZIZHIZHOU"
            }, {
                "city_id": "1508",
                "name": "\u542f\u4e1c\u5e02",
                "pinyin": "QIDONGSHI"
            }, {
                "city_id": "420",
                "name": "\u5e86\u5b89\u53bf",
                "pinyin": "QINGANXIAN"
            }, {
                "city_id": "236",
                "name": "\u9752\u5c9b\u5e02",
                "pinyin": "QINGDAOSHI"
            }, {
                "city_id": "1242",
                "name": "\u6e05\u6cb3\u53bf",
                "pinyin": "QINGHEXIAN"
            }, {
                "city_id": "1458",
                "name": "\u9752\u7530\u53bf",
                "pinyin": "QINGTIANXIAN"
            }, {
                "city_id": "2563",
                "name": "\u9752\u53bf",
                "pinyin": "QINGXIAN"
            }, {
                "city_id": "135",
                "name": "\u5e86\u9633\u5e02",
                "pinyin": "QINGYANGSHI"
            }, {
                "city_id": "197",
                "name": "\u6e05\u8fdc\u5e02",
                "pinyin": "QINGYUANSHI"
            }, {
                "city_id": "1457",
                "name": "\u5e86\u5143\u53bf",
                "pinyin": "QINGYUANXIAN"
            }, {
                "city_id": "2169",
                "name": "\u9752\u5dde\u5e02",
                "pinyin": "QINGZHOUSHI"
            }, {
                "city_id": "148",
                "name": "\u79e6\u7687\u5c9b\u5e02",
                "pinyin": "QINHUANGDAOSHI"
            }, {
                "city_id": "145",
                "name": "\u94a6\u5dde\u5e02",
                "pinyin": "QINZHOUSHI"
            }, {
                "city_id": "2358",
                "name": "\u743c\u6d77\u5e02",
                "pinyin": "QIONGHAISHI"
            }, {
                "city_id": "635",
                "name": "\u909b\u5d03\u5e02",
                "pinyin": "QIONGLAISHI"
            }, {
                "city_id": "41",
                "name": "\u9f50\u9f50\u54c8\u5c14\u5e02",
                "pinyin": "QIQIHAERSHI"
            }, {
                "city_id": "47",
                "name": "\u4e03\u53f0\u6cb3\u5e02",
                "pinyin": "QITAIHESHI"
            }, {
                "city_id": "134",
                "name": "\u6cc9\u5dde\u5e02",
                "pinyin": "QUANZHOUSHI"
            }, {
                "city_id": "249",
                "name": "\u66f2\u9756\u5e02",
                "pinyin": "QUJINGSHI"
            }, {
                "city_id": "243",
                "name": "\u8862\u5dde\u5e02",
                "pinyin": "QUZHOUSHI"
            }, {
                "city_id": "2374",
                "name": "\u4efb\u4e18\u5e02",
                "pinyin": "RENQIUSHI"
            }, {
                "city_id": "2639",
                "name": "\u4efb\u53bf",
                "pinyin": "RENXIAN"
            }, {
                "city_id": "173",
                "name": "\u65e5\u7167\u5e02",
                "pinyin": "RIZHAOSHI"
            }, {
                "city_id": "2177",
                "name": "\u8363\u6210\u5e02",
                "pinyin": "RONGCHENGSHI"
            }, {
                "city_id": "1323",
                "name": "\u5982\u4e1c\u53bf",
                "pinyin": "RUDONGXIAN"
            }, {
                "city_id": "2422",
                "name": "\u5982\u768b\u5e02",
                "pinyin": "RUGAOSHI"
            }, {
                "city_id": "1882",
                "name": "\u745e\u5b89\u5e02",
                "pinyin": "RUIANSHI"
            }, {
                "city_id": "1348",
                "name": "\u745e\u660c\u5e02",
                "pinyin": "RUICHANGSHI"
            }, {
                "city_id": "212",
                "name": "\u4e09\u95e8\u5ce1\u5e02",
                "pinyin": "SANMENXIASHI"
            }, {
                "city_id": "254",
                "name": "\u4e09\u660e\u5e02",
                "pinyin": "SANMINGSHI"
            }, {
                "city_id": "121",
                "name": "\u4e09\u4e9a\u5e02",
                "pinyin": "SANYASHI"
            }, {
                "city_id": "1667",
                "name": "\u6c99\u6cb3\u5e02",
                "pinyin": "SHAHESHI"
            }, {
                "city_id": "2382",
                "name": "\u4e0a\u8521\u53bf",
                "pinyin": "SHANGCAIXIAN"
            }, {
                "city_id": "1770",
                "name": "\u4e0a\u9ad8\u53bf",
                "pinyin": "SHANGGAOXIAN"
            }, {
                "city_id": "285",
                "name": "\u5546\u6d1b\u5e02",
                "pinyin": "SHANGLUOSHI"
            }, {
                "city_id": "154",
                "name": "\u5546\u4e18\u5e02",
                "pinyin": "SHANGQIUSHI"
            }, {
                "city_id": "364",
                "name": "\u4e0a\u9976\u5e02",
                "pinyin": "SHANGRAOSHI"
            }, {
                "city_id": "1467",
                "name": "\u4e0a\u865e\u5e02",
                "pinyin": "SHANGYUSHI"
            }, {
                "city_id": "1031",
                "name": "\u5c1a\u5fd7\u5e02",
                "pinyin": "SHANGZHISHI"
            }, {
                "city_id": "303",
                "name": "\u6c55\u5934\u5e02",
                "pinyin": "SHANTOUSHI"
            }, {
                "city_id": "339",
                "name": "\u6c55\u5c3e\u5e02",
                "pinyin": "SHANWEISHI"
            }, {
                "city_id": "137",
                "name": "\u97f6\u5173\u5e02",
                "pinyin": "SHAOGUANSHI"
            }, {
                "city_id": "293",
                "name": "\u7ecd\u5174\u5e02",
                "pinyin": "SHAOXINGSHI"
            }, {
                "city_id": "273",
                "name": "\u90b5\u9633\u5e02",
                "pinyin": "SHAOYANGSHI"
            }, {
                "city_id": "2608",
                "name": "\u6c99\u53bf",
                "pinyin": "SHAXIAN"
            }, {
                "city_id": "2202",
                "name": "\u5c04\u6d2a\u53bf",
                "pinyin": "SHEHONGXIAN"
            }, {
                "city_id": "58",
                "name": "\u6c88\u9633\u5e02",
                "pinyin": "SHENYANGSHI"
            }, {
                "city_id": "770",
                "name": "\u77f3\u6cb3\u5b50\u5e02",
                "pinyin": "SHIHEZISHI"
            }, {
                "city_id": "150",
                "name": "\u77f3\u5bb6\u5e84\u5e02",
                "pinyin": "SHIJIAZHUANGSHI"
            }, {
                "city_id": "1581",
                "name": "\u77f3\u72ee\u5e02",
                "pinyin": "SHISHISHI"
            }, {
                "city_id": "216",
                "name": "\u5341\u5830\u5e02",
                "pinyin": "SHIYANSHI"
            }, {
                "city_id": "335",
                "name": "\u77f3\u5634\u5c71\u5e02",
                "pinyin": "SHIZUISHANSHI"
            }, {
                "city_id": "1412",
                "name": "\u5bff\u5149\u5e02",
                "pinyin": "SHOUGUANGSHI"
            }, {
                "city_id": "490",
                "name": "\u53cc\u9633\u533a",
                "pinyin": "SHUANGYANGQU"
            }, {
                "city_id": "45",
                "name": "\u53cc\u9e2d\u5c71\u5e02",
                "pinyin": "SHUANGYASHANSHI"
            }, {
                "city_id": "2598",
                "name": "\u8212\u57ce\u53bf",
                "pinyin": "SHUCHENGXIAN"
            }, {
                "city_id": "477",
                "name": "\u8212\u5170\u5e02",
                "pinyin": "SHULANSHI"
            }, {
                "city_id": "237",
                "name": "\u6714\u5dde\u5e02",
                "pinyin": "SHUOZHOUSHI"
            }, {
                "city_id": "1326",
                "name": "\u6cd7\u6d2a\u53bf",
                "pinyin": "SIHONGXIAN"
            }, {
                "city_id": "56",
                "name": "\u56db\u5e73\u5e02",
                "pinyin": "SIPINGSHI"
            }, {
                "city_id": "1742",
                "name": "\u6cd7\u9633\u53bf",
                "pinyin": "SIYANGXIAN"
            }, {
                "city_id": "52",
                "name": "\u677e\u539f\u5e02",
                "pinyin": "SONGYUANSHI"
            }, {
                "city_id": "463",
                "name": "\u7ee5\u82ac\u6cb3\u5e02",
                "pinyin": "SUIFENHESHI"
            }, {
                "city_id": "44",
                "name": "\u7ee5\u5316\u5e02",
                "pinyin": "SUIHUASHI"
            }, {
                "city_id": "330",
                "name": "\u9042\u5b81\u5e02",
                "pinyin": "SUININGSHI"
            }, {
                "city_id": "1743",
                "name": "\u7762\u5b81\u53bf",
                "pinyin": "SUININGXIAN"
            }, {
                "city_id": "2058",
                "name": "\u7762\u53bf",
                "pinyin": "SUIXIAN"
            }, {
                "city_id": "2496",
                "name": "\u6fc9\u6eaa\u53bf",
                "pinyin": "SUIXIXIAN"
            }, {
                "city_id": "371",
                "name": "\u968f\u5dde\u5e02",
                "pinyin": "SUIZHOUSHI"
            }, {
                "city_id": "2378",
                "name": "\u8083\u5b81\u53bf",
                "pinyin": "SUNINGXIAN"
            }, {
                "city_id": "406",
                "name": "\u5b59\u5434\u53bf",
                "pinyin": "SUNWUXIAN"
            }, {
                "city_id": "277",
                "name": "\u5bbf\u8fc1\u5e02",
                "pinyin": "SUQIANSHI"
            }, {
                "city_id": "224",
                "name": "\u82cf\u5dde\u5e02",
                "pinyin": "SUZHOUSHI"
            }, {
                "city_id": "370",
                "name": "\u5bbf\u5dde\u5e02",
                "pinyin": "SUZHOUSHI"
            }, {
                "city_id": "94",
                "name": "\u5854\u57ce\u5730\u533a",
                "pinyin": "TACHENGDIQU"
            }, {
                "city_id": "325",
                "name": "\u6cf0\u5b89\u5e02",
                "pinyin": "TAIANSHI"
            }, {
                "city_id": "2295",
                "name": "\u53f0\u5b89\u53bf",
                "pinyin": "TAIANXIAN"
            }, {
                "city_id": "1934",
                "name": "\u592a\u4ed3\u5e02",
                "pinyin": "TAICANGSHI"
            }, {
                "city_id": "1476",
                "name": "\u592a\u548c\u53bf",
                "pinyin": "TAIHEXIAN"
            }, {
                "city_id": "1154",
                "name": "\u53f0\u5c71\u5e02",
                "pinyin": "TAISHANSHI"
            }, {
                "city_id": "2894",
                "name": "\u6cf0\u5174\u5e02",
                "pinyin": "TAIXINGSHI"
            }, {
                "city_id": "176",
                "name": "\u592a\u539f\u5e02",
                "pinyin": "TAIYUANSHI"
            }, {
                "city_id": "244",
                "name": "\u53f0\u5dde\u5e02",
                "pinyin": "TAIZHOUSHI"
            }, {
                "city_id": "276",
                "name": "\u6cf0\u5dde\u5e02",
                "pinyin": "TAIZHOUSHI"
            }, {
                "city_id": "1935",
                "name": "\u90ef\u57ce\u53bf",
                "pinyin": "TANCHENGXIAN"
            }, {
                "city_id": "1920",
                "name": "\u5510\u6d77\u53bf",
                "pinyin": "TANGHAIXIAN"
            }, {
                "city_id": "265",
                "name": "\u5510\u5c71\u5e02",
                "pinyin": "TANGSHANSHI"
            }, {
                "city_id": "2636",
                "name": "\u5510\u53bf",
                "pinyin": "TANGXIAN"
            }, {
                "city_id": "467",
                "name": "\u6d2e\u5357\u5e02",
                "pinyin": "TAONANSHI"
            }, {
                "city_id": "332",
                "name": "\u5929\u6d25\u5e02",
                "pinyin": "TIANJINSHI"
            }, {
                "city_id": "2654",
                "name": "\u5929\u95e8\u5e02",
                "pinyin": "TIANMENSHI"
            }, {
                "city_id": "196",
                "name": "\u5929\u6c34\u5e02",
                "pinyin": "TIANSHUISHI"
            }, {
                "city_id": "2219",
                "name": "\u5929\u53f0\u53bf",
                "pinyin": "TIANTAIXIAN"
            }, {
                "city_id": "60",
                "name": "\u94c1\u5cad\u5e02",
                "pinyin": "TIELINGSHI"
            }, {
                "city_id": "232",
                "name": "\u94dc\u5ddd\u5e02",
                "pinyin": "TONGCHUANSHI"
            }, {
                "city_id": "439",
                "name": "\u901a\u6cb3\u53bf",
                "pinyin": "TONGHEXIAN"
            }, {
                "city_id": "165",
                "name": "\u901a\u5316\u5e02",
                "pinyin": "TONGHUASHI"
            }, {
                "city_id": "64",
                "name": "\u901a\u8fbd\u5e02",
                "pinyin": "TONGLIAOSHI"
            }, {
                "city_id": "337",
                "name": "\u94dc\u9675\u5e02",
                "pinyin": "TONGLINGSHI"
            }, {
                "city_id": "1464",
                "name": "\u6850\u5e90\u53bf",
                "pinyin": "TONGLUXIAN"
            }, {
                "city_id": "205",
                "name": "\u94dc\u4ec1\u5730\u533a",
                "pinyin": "TONGRENDIQU"
            }, {
                "city_id": "2584",
                "name": "\u6850\u4e61\u5e02",
                "pinyin": "TONGXIANGSHI"
            }, {
                "city_id": "89",
                "name": "\u5410\u9c81\u756a\u5730\u533a",
                "pinyin": "TULUFANDIQU"
            }, {
                "city_id": "792",
                "name": "\u56fe\u6728\u8212\u514b\u5e02",
                "pinyin": "TUMUSHUKESHI"
            }, {
                "city_id": "1038",
                "name": "\u7a81\u6cc9\u53bf",
                "pinyin": "TUQUANXIAN"
            }
        ],
        "UVWXYZ": [
            {
                "city_id": "1216",
                "name": "\u4e07\u5b81\u5e02",
                "pinyin": "WANNINGSHI"
            }, {
                "city_id": "287",
                "name": "\u6f4d\u574a\u5e02",
                "pinyin": "WEIFANGSHI"
            }, {
                "city_id": "175",
                "name": "\u5a01\u6d77\u5e02",
                "pinyin": "WEIHAISHI"
            }, {
                "city_id": "170",
                "name": "\u6e2d\u5357\u5e02",
                "pinyin": "WEINANSHI"
            }, {
                "city_id": "1001",
                "name": "\u5a01\u5b81\u5f5d\u65cf\u56de\u65cf\u82d7\u65cf\u81ea\u6cbb\u53bf",
                "pinyin": "WEININGYIZUHUIZUMIAOZUZIZHIXIAN"
            }, {
                "city_id": "2879",
                "name": "\u5fae\u5c71\u53bf",
                "pinyin": "WEISHANXIAN"
            }, {
                "city_id": "2393",
                "name": "\u5c09\u6c0f\u53bf",
                "pinyin": "WEISHIXIAN"
            }, {
                "city_id": "1665",
                "name": "\u5a01\u53bf",
                "pinyin": "WEIXIAN"
            }, {
                "city_id": "2758",
                "name": "\u6587\u660c\u5e02",
                "pinyin": "WENCHANGSHI"
            }, {
                "city_id": "2209",
                "name": "\u6587\u6210\u53bf",
                "pinyin": "WENCHENGXIAN"
            }, {
                "city_id": "1473",
                "name": "\u6e29\u5cad\u5e02",
                "pinyin": "WENLINGSHI"
            }, {
                "city_id": "1819",
                "name": "\u6c76\u4e0a\u53bf",
                "pinyin": "WENSHANGXIAN"
            }, {
                "city_id": "177",
                "name": "\u6587\u5c71\u58ee\u65cf\u82d7\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "WENSHANZHUANGZUMIAOZUZIZHIZHOU"
            }, {
                "city_id": "178",
                "name": "\u6e29\u5dde\u5e02",
                "pinyin": "WENZHOUSHI"
            }, {
                "city_id": "1246",
                "name": "\u6b66\u5b89\u5e02",
                "pinyin": "WUANSHI"
            }, {
                "city_id": "409",
                "name": "\u4e94\u5927\u8fde\u6c60\u5e02",
                "pinyin": "WUDALIANCHISHI"
            }, {
                "city_id": "123",
                "name": "\u4e4c\u6d77\u5e02",
                "pinyin": "WUHAISHI"
            }, {
                "city_id": "218",
                "name": "\u6b66\u6c49\u5e02",
                "pinyin": "WUHANSHI"
            }, {
                "city_id": "129",
                "name": "\u829c\u6e56\u5e02",
                "pinyin": "WUHUSHI"
            }, {
                "city_id": "2500",
                "name": "\u829c\u6e56\u53bf",
                "pinyin": "WUHUXIAN"
            }, {
                "city_id": "2284",
                "name": "\u5434\u6c5f\u5e02",
                "pinyin": "WUJIANGSHI"
            }, {
                "city_id": "168",
                "name": "\u4e4c\u5170\u5bdf\u5e03\u5e02",
                "pinyin": "WULANCHABUSHI"
            }, {
                "city_id": "1042",
                "name": "\u4e4c\u5170\u6d69\u7279\u5e02",
                "pinyin": "WULANHAOTESHI"
            }, {
                "city_id": "92",
                "name": "\u4e4c\u9c81\u6728\u9f50\u5e02",
                "pinyin": "WULUMUQISHI"
            }, {
                "city_id": "2264",
                "name": "\u5434\u6865\u53bf",
                "pinyin": "WUQIAOXIAN"
            }, {
                "city_id": "118",
                "name": "\u6b66\u5a01\u5e02",
                "pinyin": "WUWEISHI"
            }, {
                "city_id": "1951",
                "name": "\u65e0\u4e3a\u53bf",
                "pinyin": "WUWEIXIAN"
            }, {
                "city_id": "317",
                "name": "\u65e0\u9521\u5e02",
                "pinyin": "WUXISHI"
            }, {
                "city_id": "322",
                "name": "\u5434\u5fe0\u5e02",
                "pinyin": "WUZHONGSHI"
            }, {
                "city_id": "304",
                "name": "\u68a7\u5dde\u5e02",
                "pinyin": "WUZHOUSHI"
            }, {
                "city_id": "194",
                "name": "\u53a6\u95e8\u5e02",
                "pinyin": "XIAMENSHI"
            }, {
                "city_id": "2664",
                "name": "\u54cd\u6c34\u53bf",
                "pinyin": "XIANGSHUIXIAN"
            }, {
                "city_id": "313",
                "name": "\u6e58\u6f6d\u5e02",
                "pinyin": "XIANGTANSHI"
            }, {
                "city_id": "2815",
                "name": "\u6e58\u4e61\u5e02",
                "pinyin": "XIANGXIANGSHI"
            }, {
                "city_id": "156",
                "name": "\u8944\u9633\u5e02",
                "pinyin": "XIANGYANGSHI"
            }, {
                "city_id": "1874",
                "name": "\u4ed9\u5c45\u53bf",
                "pinyin": "XIANJUXIAN"
            }, {
                "city_id": "362",
                "name": "\u54b8\u5b81\u5e02",
                "pinyin": "XIANNINGSHI"
            }, {
                "city_id": "233",
                "name": "\u897f\u5b89\u5e02",
                "pinyin": "XIANSHI"
            }, {
                "city_id": "1713",
                "name": "\u4ed9\u6843\u5e02",
                "pinyin": "XIANTAOSHI"
            }, {
                "city_id": "2038",
                "name": "\u732e\u53bf",
                "pinyin": "XIANXIAN"
            }, {
                "city_id": "323",
                "name": "\u54b8\u9633\u5e02",
                "pinyin": "XIANYANGSHI"
            }, {
                "city_id": "310",
                "name": "\u5b5d\u611f\u5e02",
                "pinyin": "XIAOGANSHI"
            }, {
                "city_id": "2489",
                "name": "\u8427\u5c71\u533a",
                "pinyin": "XIAOSHANQU"
            }, {
                "city_id": "1860",
                "name": "\u5b5d\u4e49\u5e02",
                "pinyin": "XIAOYISHI"
            }, {
                "city_id": "684",
                "name": "\u897f\u660c\u5e02",
                "pinyin": "XICHANGSHI"
            }, {
                "city_id": "63",
                "name": "\u9521\u6797\u90ed\u52d2\u76df",
                "pinyin": "XILINGUOLEMENG"
            }, {
                "city_id": "2068",
                "name": "\u65b0\u8521\u53bf",
                "pinyin": "XINCAIXIAN"
            }, {
                "city_id": "62",
                "name": "\u5174\u5b89\u76df",
                "pinyin": "XINGANMENG"
            }, {
                "city_id": "1324",
                "name": "\u5174\u5316\u5e02",
                "pinyin": "XINGHUASHI"
            }, {
                "city_id": "2150",
                "name": "\u5174\u5e73\u5e02",
                "pinyin": "XINGPINGSHI"
            }, {
                "city_id": "266",
                "name": "\u90a2\u53f0\u5e02",
                "pinyin": "XINGTAISHI"
            }, {
                "city_id": "2075",
                "name": "\u8365\u9633\u5e02",
                "pinyin": "XINGYANGSHI"
            }, {
                "city_id": "1535",
                "name": "\u5174\u4e49\u5e02",
                "pinyin": "XINGYISHI"
            }, {
                "city_id": "1762",
                "name": "\u661f\u5b50\u53bf",
                "pinyin": "XINGZIXIAN"
            }, {
                "city_id": "66",
                "name": "\u897f\u5b81\u5e02",
                "pinyin": "XININGSHI"
            }, {
                "city_id": "2368",
                "name": "\u8f9b\u96c6\u5e02",
                "pinyin": "XINJISHI"
            }, {
                "city_id": "519",
                "name": "\u65b0\u6c11\u5e02",
                "pinyin": "XINMINSHI"
            }, {
                "city_id": "2390",
                "name": "\u65b0\u5bc6\u5e02",
                "pinyin": "XINMISHI"
            }, {
                "city_id": "2455",
                "name": "\u65b0\u6cf0\u5e02",
                "pinyin": "XINTAISHI"
            }, {
                "city_id": "152",
                "name": "\u65b0\u4e61\u5e02",
                "pinyin": "XINXIANGSHI"
            }, {
                "city_id": "214",
                "name": "\u4fe1\u9633\u5e02",
                "pinyin": "XINYANGSHI"
            }, {
                "city_id": "2421",
                "name": "\u65b0\u6c82\u5e02",
                "pinyin": "XINYISHI"
            }, {
                "city_id": "164",
                "name": "\u65b0\u4f59\u5e02",
                "pinyin": "XINYUSHI"
            }, {
                "city_id": "2652",
                "name": "\u65b0\u90d1\u5e02",
                "pinyin": "XINZHENGSHI"
            }, {
                "city_id": "367",
                "name": "\u5ffb\u5dde\u5e02",
                "pinyin": "XINZHOUSHI"
            }, {
                "city_id": "1650",
                "name": "\u96c4\u53bf",
                "pinyin": "XIONGXIAN"
            }, {
                "city_id": "1266",
                "name": "\u897f\u5e73\u53bf",
                "pinyin": "XIPINGXIAN"
            }, {
                "city_id": "2875",
                "name": "\u4fee\u6c34\u53bf",
                "pinyin": "XIUSHUIXIAN"
            }, {
                "city_id": "2441",
                "name": "\u5cab\u5ca9\u6ee1\u65cf\u81ea\u6cbb\u53bf",
                "pinyin": "XIUYANMANZUZIZHIXIAN"
            }, {
                "city_id": "190",
                "name": "\u5ba3\u57ce\u5e02",
                "pinyin": "XUANCHENGSHI"
            }, {
                "city_id": "155",
                "name": "\u8bb8\u660c\u5e02",
                "pinyin": "XUCHANGSHI"
            }, {
                "city_id": "1756",
                "name": "\u76f1\u7719\u53bf",
                "pinyin": "XUYIXIAN"
            }, {
                "city_id": "316",
                "name": "\u5f90\u5dde\u5e02",
                "pinyin": "XUZHOUSHI"
            }, {
                "city_id": "539",
                "name": "\u7259\u514b\u77f3\u5e02",
                "pinyin": "YAKESHISHI"
            }, {
                "city_id": "284",
                "name": "\u5ef6\u5b89\u5e02",
                "pinyin": "YANANSHI"
            }, {
                "city_id": "54",
                "name": "\u5ef6\u8fb9\u671d\u9c9c\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "YANBIANCHAOXIANZUZIZHIZHOU"
            }, {
                "city_id": "223",
                "name": "\u76d0\u57ce\u5e02",
                "pinyin": "YANCHENGSHI"
            }, {
                "city_id": "1489",
                "name": "\u76d0\u6c60\u53bf",
                "pinyin": "YANCHIXIAN"
            }, {
                "city_id": "199",
                "name": "\u9633\u6c5f\u5e02",
                "pinyin": "YANGJIANGSHI"
            }, {
                "city_id": "357",
                "name": "\u9633\u6cc9\u5e02",
                "pinyin": "YANGQUANSHI"
            }, {
                "city_id": "1673",
                "name": "\u9633\u539f\u53bf",
                "pinyin": "YANGYUANXIAN"
            }, {
                "city_id": "2820",
                "name": "\u626c\u4e2d\u5e02",
                "pinyin": "YANGZHONGSHI"
            }, {
                "city_id": "346",
                "name": "\u626c\u5dde\u5e02",
                "pinyin": "YANGZHOUSHI"
            }, {
                "city_id": "495",
                "name": "\u5ef6\u5409\u5e02",
                "pinyin": "YANJISHI"
            }, {
                "city_id": "1658",
                "name": "\u76d0\u5c71\u53bf",
                "pinyin": "YANSHANXIAN"
            }, {
                "city_id": "452",
                "name": "\u5ef6\u5bff\u53bf",
                "pinyin": "YANSHOUXIAN"
            }, {
                "city_id": "326",
                "name": "\u70df\u53f0\u5e02",
                "pinyin": "YANTAISHI"
            }, {
                "city_id": "186",
                "name": "\u5b9c\u5bbe\u5e02",
                "pinyin": "YIBINSHI"
            }, {
                "city_id": "270",
                "name": "\u5b9c\u660c\u5e02",
                "pinyin": "YICHANGSHI"
            }, {
                "city_id": "40",
                "name": "\u4f0a\u6625\u5e02",
                "pinyin": "YICHUNSHI"
            }, {
                "city_id": "278",
                "name": "\u5b9c\u6625\u5e02",
                "pinyin": "YICHUNSHI"
            }, {
                "city_id": "2405",
                "name": "\u5b9c\u90fd\u5e02",
                "pinyin": "YIDUSHI"
            }, {
                "city_id": "90",
                "name": "\u4f0a\u7281\u54c8\u8428\u514b\u81ea\u6cbb\u5dde",
                "pinyin": "YILIHASAKEZIZHIZHOU"
            }, {
                "city_id": "360",
                "name": "\u94f6\u5ddd\u5e02",
                "pinyin": "YINCHUANSHI"
            }, {
                "city_id": "1708",
                "name": "\u5e94\u57ce\u5e02",
                "pinyin": "YINGCHENGSHI"
            }, {
                "city_id": "281",
                "name": "\u8425\u53e3\u5e02",
                "pinyin": "YINGKOUSHI"
            }, {
                "city_id": "279",
                "name": "\u9e70\u6f6d\u5e02",
                "pinyin": "YINGTANSHI"
            }, {
                "city_id": "491",
                "name": "\u4f0a\u901a\u6ee1\u65cf\u81ea\u6cbb\u53bf",
                "pinyin": "YITONGMANZUZIZHIXIAN"
            }, {
                "city_id": "2217",
                "name": "\u4e49\u4e4c\u5e02",
                "pinyin": "YIWUSHI"
            }, {
                "city_id": "1336",
                "name": "\u5b9c\u5174\u5e02",
                "pinyin": "YIXINGSHI"
            }, {
                "city_id": "272",
                "name": "\u76ca\u9633\u5e02",
                "pinyin": "YIYANGSHI"
            }, {
                "city_id": "2424",
                "name": "\u4eea\u5f81\u5e02",
                "pinyin": "YIZHENGSHI"
            }, {
                "city_id": "1136",
                "name": "\u6c38\u5b89\u5e02",
                "pinyin": "YONGANSHI"
            }, {
                "city_id": "1137",
                "name": "\u6c38\u6625\u53bf",
                "pinyin": "YONGCHUNXIAN"
            }, {
                "city_id": "488",
                "name": "\u6c38\u5409\u53bf",
                "pinyin": "YONGJIXIAN"
            }, {
                "city_id": "2830",
                "name": "\u6c38\u5eb7\u5e02",
                "pinyin": "YONGKANGSHI"
            }, {
                "city_id": "314",
                "name": "\u6c38\u5dde\u5e02",
                "pinyin": "YONGZHOUSHI"
            }, {
                "city_id": "1977",
                "name": "\u5c24\u6eaa\u53bf",
                "pinyin": "YOUXIXIAN"
            }, {
                "city_id": "2658",
                "name": "\u6c85\u6c5f\u5e02",
                "pinyin": "YUANJIANGSHI"
            }, {
                "city_id": "1301",
                "name": "\u6c85\u9675\u53bf",
                "pinyin": "YUANLINGXIAN"
            }, {
                "city_id": "1845",
                "name": "\u539f\u5e73\u5e02",
                "pinyin": "YUANPINGSHI"
            }, {
                "city_id": "1664",
                "name": "\u5143\u6c0f\u53bf",
                "pinyin": "YUANSHIXIAN"
            }, {
                "city_id": "2487",
                "name": "\u4e50\u6e05\u5e02",
                "pinyin": "YUEQINGSHI"
            }, {
                "city_id": "220",
                "name": "\u5cb3\u9633\u5e02",
                "pinyin": "YUEYANGSHI"
            }, {
                "city_id": "1885",
                "name": "\u7389\u73af\u53bf",
                "pinyin": "YUHUANXIAN"
            }, {
                "city_id": "231",
                "name": "\u6986\u6797\u5e02",
                "pinyin": "YULINSHI"
            }, {
                "city_id": "361",
                "name": "\u7389\u6797\u5e02",
                "pinyin": "YULINSHI"
            }, {
                "city_id": "328",
                "name": "\u8fd0\u57ce\u5e02",
                "pinyin": "YUNCHENGSHI"
            }, {
                "city_id": "258",
                "name": "\u4e91\u6d6e\u5e02",
                "pinyin": "YUNFUSHI"
            }, {
                "city_id": "2246",
                "name": "\u4e91\u9704\u53bf",
                "pinyin": "YUNXIAOXIAN"
            }, {
                "city_id": "469",
                "name": "\u6986\u6811\u5e02",
                "pinyin": "YUSHUSHI"
            }, {
                "city_id": "71",
                "name": "\u7389\u6811\u85cf\u65cf\u81ea\u6cbb\u5dde",
                "pinyin": "YUSHUZANGZUZIZHIZHOU"
            }, {
                "city_id": "2564",
                "name": "\u7389\u7530\u53bf",
                "pinyin": "YUTIANXIAN"
            }, {
                "city_id": "1224",
                "name": "\u851a\u53bf",
                "pinyin": "YUXIAN"
            }, {
                "city_id": "106",
                "name": "\u7389\u6eaa\u5e02",
                "pinyin": "YUXISHI"
            }, {
                "city_id": "2215",
                "name": "\u4f59\u59da\u5e02",
                "pinyin": "YUYAOSHI"
            }, {
                "city_id": "2812",
                "name": "\u79b9\u5dde\u5e02",
                "pinyin": "YUZHOUSHI"
            }, {
                "city_id": "1241",
                "name": "\u67a3\u5f3a\u53bf",
                "pinyin": "ZAOQIANGXIAN"
            }, {
                "city_id": "2567",
                "name": "\u67a3\u9633\u5e02",
                "pinyin": "ZAOYANGSHI"
            }, {
                "city_id": "172",
                "name": "\u67a3\u5e84\u5e02",
                "pinyin": "ZAOZHUANGSHI"
            }, {
                "city_id": "1025",
                "name": "\u624e\u8d49\u7279\u65d7",
                "pinyin": "ZHALAITEQI"
            }, {
                "city_id": "1035",
                "name": "\u624e\u5170\u5c6f\u5e02",
                "pinyin": "ZHALANTUNSHI"
            }, {
                "city_id": "2665",
                "name": "\u5f20\u5bb6\u6e2f\u5e02",
                "pinyin": "ZHANGJIAGANGSHI"
            }, {
                "city_id": "312",
                "name": "\u5f20\u5bb6\u754c\u5e02",
                "pinyin": "ZHANGJIAJIESHI"
            }, {
                "city_id": "264",
                "name": "\u5f20\u5bb6\u53e3\u5e02",
                "pinyin": "ZHANGJIAKOUSHI"
            }, {
                "city_id": "2458",
                "name": "\u7ae0\u4e18\u5e02",
                "pinyin": "ZHANGQIUSHI"
            }, {
                "city_id": "2129",
                "name": "\u6a1f\u6811\u5e02",
                "pinyin": "ZHANGSHUSHI"
            }, {
                "city_id": "515",
                "name": "\u5f70\u6b66\u53bf",
                "pinyin": "ZHANGWUXIAN"
            }, {
                "city_id": "117",
                "name": "\u5f20\u6396\u5e02",
                "pinyin": "ZHANGYESHI"
            }, {
                "city_id": "255",
                "name": "\u6f33\u5dde\u5e02",
                "pinyin": "ZHANGZHOUSHI"
            }, {
                "city_id": "198",
                "name": "\u6e5b\u6c5f\u5e02",
                "pinyin": "ZHANJIANGSHI"
            }, {
                "city_id": "1020",
                "name": "\u8087\u4e1c\u5e02",
                "pinyin": "ZHAODONGSHI"
            }, {
                "city_id": "338",
                "name": "\u8087\u5e86\u5e02",
                "pinyin": "ZHAOQINGSHI"
            }, {
                "city_id": "336",
                "name": "\u662d\u901a\u5e02",
                "pinyin": "ZHAOTONGSHI"
            }, {
                "city_id": "2692",
                "name": "\u62db\u8fdc\u5e02",
                "pinyin": "ZHAOYUANSHI"
            }, {
                "city_id": "268",
                "name": "\u90d1\u5dde\u5e02",
                "pinyin": "ZHENGZHOUSHI"
            }, {
                "city_id": "160",
                "name": "\u9547\u6c5f\u5e02",
                "pinyin": "ZHENJIANGSHI"
            }, {
                "city_id": "1680",
                "name": "\u4e2d\u725f\u53bf",
                "pinyin": "ZHONGMOUXIAN"
            }, {
                "city_id": "187",
                "name": "\u4e2d\u5c71\u5e02",
                "pinyin": "ZHONGSHANSHI"
            }, {
                "city_id": "181",
                "name": "\u4e2d\u536b\u5e02",
                "pinyin": "ZHONGWEISHI"
            }, {
                "city_id": "2080",
                "name": "\u949f\u7965\u5e02",
                "pinyin": "ZHONGXIANGSHI"
            }, {
                "city_id": "308",
                "name": "\u5468\u53e3\u5e02",
                "pinyin": "ZHOUKOUSHI"
            }, {
                "city_id": "245",
                "name": "\u821f\u5c71\u5e02",
                "pinyin": "ZHOUSHANSHI"
            }, {
                "city_id": "140",
                "name": "\u73e0\u6d77\u5e02",
                "pinyin": "ZHUHAISHI"
            }, {
                "city_id": "2708",
                "name": "\u8bf8\u66a8\u5e02",
                "pinyin": "ZHUJISHI"
            }, {
                "city_id": "269",
                "name": "\u9a7b\u9a6c\u5e97\u5e02",
                "pinyin": "ZHUMADIANSHI"
            }, {
                "city_id": "2234",
                "name": "\u6dbf\u5dde\u5e02",
                "pinyin": "ZHUOZHOUSHI"
            }, {
                "city_id": "222",
                "name": "\u682a\u6d32\u5e02",
                "pinyin": "ZHUZHOUSHI"
            }, {
                "city_id": "354",
                "name": "\u6dc4\u535a\u5e02",
                "pinyin": "ZIBOSHI"
            }, {
                "city_id": "78",
                "name": "\u81ea\u8d21\u5e02",
                "pinyin": "ZIGONGSHI"
            }, {
                "city_id": "242",
                "name": "\u8d44\u9633\u5e02",
                "pinyin": "ZIYANGSHI"
            }, {
                "city_id": "647",
                "name": "\u8d44\u4e2d\u53bf",
                "pinyin": "ZIZHONGXIAN"
            }, {
                "city_id": "1401",
                "name": "\u90b9\u57ce\u5e02",
                "pinyin": "ZOUCHENGSHI"
            }, {
                "city_id": "2175",
                "name": "\u90b9\u5e73\u53bf",
                "pinyin": "ZOUPINGXIAN"
            }, {
                "city_id": "2260",
                "name": "\u9075\u5316\u5e02",
                "pinyin": "ZUNHUASHI"
            }, {
                "city_id": "262",
                "name": "\u9075\u4e49\u5e02",
                "pinyin": "ZUNYISHI"
            }, {
                "city_id": "2024",
                "name": "\u9075\u4e49\u53bf",
                "pinyin": "ZUNYIXIAN"
            }
        ]
    }
}
