export const DATA_SOURCE_LIST = 'getDataSourceList'
export const DEPARTMENT_INFO = 'getDepartmentInfo'
export const PUSH_PACKAGES = 'getPushPackages'
export const JUMP_TARGET_LIST = 'getJumpTargetList'
export const SET_FORM_DATA = 'setFormData'
export const SET_FORM_PAGE_DATA = 'setFormPageData'
export const CREATE_PACKAGE_DIALOG = 'createPackageDialog'
export const EDIT_PACKAGE_DIALOG = 'editPackageDialog'
export const CLOSE_PACKAGE_DIALOG = 'closePackageDialog'
export const GET_SELECTED_DATA_SOURCES = 'getSelectedDataSource'
export const GET_SELECTED_CITY_IDS = 'getSelectedCityIds'
export const GET_DEPARTMENT_VALUE = 'getDepartmentValue'
export const CHANGE_DISPLAY_TYPE = 'changeDisplayType'
export const CHANGE_TOTAL_NUM = 'changeTotalNum'
export const CHANGE_COUPON_DATE= 'changeCouponDate'
export const GET_ACTIVITY_NAME = 'getActivityName'
export const GET_SUBMIT_DATA = 'getSubmitData'
//dialog
export const CHANGE_PUSH_FLAG = 'changePushFlag'
export const CHANGE_SMS_FLAG = 'changeSmsFlag'
export const SET_PUSH_CONTENT = 'setPushContent'
export const SET_JUMP_TARGET_VALUE= 'setJumpTargetValue'
export const SET_PUSH_LINK= 'setPushLink'
export const SET_PUSH_TIME = 'setPushTime'
export const SET_SMS_CONTENT = 'setSmsContent'
export const SET_SMS_TIME = 'setSmsTime'
export const SET_USER_NUM = 'setUserNum'
export const GET_DIALOG_SUBMIT_DATA = 'getDialogSubmitData'
export const DELETE_PACKAGE= 'deletePackage'
//table
export const GET_PUSH_PACKAGES = 'getPushPackages'

export const COUPON_DATE_FORMAT = 'couponDateFormat'