export default {
    errno: 0,
    errmsg: "",
    data: {
        total: 791,
        item: [
        {
            id: "1992307",
            city_names: "北京市",
            city_id: "131",
            activity_name: "便利店大酬宾返券活动",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "董天宇",
            start_time: "2017-06-13 00:00:00",
            end_time: "2017-08-31 23:59:59",
            activity_status: "2",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1992307",
            city_names: "北京市",
            city_id: "131",
            activity_name: "便利店大酬宾返券活动",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "董天宇",
            start_time: "2017-06-13 00:00:00",
            end_time: "2017-08-31 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1990476",
            city_names: "霍邱县",
            city_id: "2498",
            activity_name: "霍邱下单返券活动",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "包亮亮",
            start_time: "2017-06-12 16:03:29",
            end_time: "2017-06-26 16:03:29",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1984689",
            city_names: "兴化市",
            city_id: "1324",
            activity_name: "兴化云小苗下单返券20-10互斥",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "刘欣",
            start_time: "2017-06-10 00:00:00",
            end_time: "2017-06-30 23:59:59",
            activity_status: "2",
            is_owner: 1,
            shop_num: 1,
            type_desc: ["实际在线支付满15元返10元商家券"],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1973927",
            city_names: "沈阳市",
            city_id: "58",
            activity_name: "果飘飘奶茶进店满15送2元代金券",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "彭伟柱",
            start_time: "2017-06-07 18:38:48",
            end_time: "2017-10-06 18:38:48",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1963410",
            city_names: "大连市",
            city_id: "167",
            activity_name: "大连下单反卷",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "张强",
            start_time: "2017-06-05 00:00:00",
            end_time: "2017-06-11 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1949329",
            city_names: "赣州市",
            city_id: "365",
            activity_name: "赣州满50-3元",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "gzwm230",
            start_time: "2017-06-02 00:00:00",
            end_time: "2017-06-30 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1949205",
            city_names: "哈尔滨市",
            city_id: "48",
            activity_name: "吃到嗨，下单返红包",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "裴松",
            start_time: "2017-06-02 09:48:29",
            end_time: "2017-06-08 09:48:29",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1942075",
            city_names: "全国",
            city_id: "1",
            activity_name: "百利家100返5",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "魏明潭",
            start_time: "2017-06-01 00:00:00",
            end_time: "2017-06-30 23:59:59",
            activity_status: "2",
            is_owner: 1,
            shop_num: 36,
            type_desc: ["实际在线支付满0元返5元商家券"],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1939756",
            city_names: "迁安市",
            city_id: "1223",
            activity_name: "人人赚：打开APP点击右下角【我的】【分享有礼】【面对面邀请】每成功邀请一个新客户下单返6元",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "李国梁",
            start_time: "2017-05-31 00:00:00",
            end_time: "2017-09-08 00:00:00",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1938725",
            city_names: "北京市",
            city_id: "131",
            activity_name: "花舍餐饮管理（北京）有限公司",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "王磊",
            start_time: "2017-06-01 00:00:00",
            end_time: "2017-08-25 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1935711",
            city_names: "西安市",
            city_id: "233",
            activity_name: "九九精武",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "liuwenboa",
            start_time: "2017-05-29 00:00:00",
            end_time: "2017-09-05 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1930231",
            city_names: "武汉市",
            city_id: "218",
            activity_name: "满35元送三元现金券",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "梅仁锦",
            start_time: "2017-05-27 00:00:00",
            end_time: "2017-05-27 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1927136",
            city_names: "全国",
            city_id: "1",
            activity_name: "个个鲜满59返25元",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "杨茂洪",
            start_time: "2017-05-27 00:00:00",
            end_time: "2017-05-31 23:59:59",
            activity_status: "3",
            is_owner: 1,
            shop_num: 29,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1923128",
            city_names: "鸡西市",
            city_id: "46",
            activity_name: "鸡西下单返券",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "刘超",
            start_time: "2017-05-25 14:33:15",
            end_time: "2017-05-31 23:59:00",
            activity_status: "3",
            is_owner: 1,
            shop_num: 43,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1913639",
            city_names: "镇江市",
            city_id: "160",
            activity_name: "下单返券测试",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "常小许",
            start_time: "2017-05-23 00:00:00",
            end_time: "2017-05-31 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1913569",
            city_names: "镇江市",
            city_id: "160",
            activity_name: "镇江下单返券测试",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "常小许",
            start_time: "2017-05-23 00:00:00",
            end_time: "2017-05-31 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1913551",
            city_names: "泰州市",
            city_id: "276",
            activity_name: "泰州下单返券",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "刘欣",
            start_time: "2017-05-23 00:00:00",
            end_time: "2017-05-29 23:59:59",
            activity_status: "1",
            is_owner: 1,
            shop_num: 0,
            type_desc: ["实际在线支付满1元返3元商家券"],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1911149",
            city_names: "衡阳市",
            city_id: "159",
            activity_name: "衡阳5月下单返红包30-5",
            activity_description: "更多优惠活动等你来~~",
            activity_owner: "吕豪",
            start_time: "2017-05-23 00:00:00",
            end_time: "2017-05-31 23:59:59",
            activity_status: "3",
            is_owner: 1,
            shop_num: 11,
            type_desc: [],
            smart: 0,
            approve_status: 5
        },
        {
            id: "1898890",
            city_names: "通化市",
            city_id: "165",
            activity_name: "25元返3元代金券",
            activity_description: "百度外卖用户专享",
            activity_owner: "wangdandan02",
            start_time: "2017-05-20 00:00:00",
            end_time: "2017-06-20 23:59:59",
            activity_status: "2",
            is_owner: 1,
            shop_num: 1,
            type_desc: ["实际在线支付满25元返3元商家券"],
            smart: 0,
            approve_status: 5
        }],
        curpage: 1,
        perpage: 20,
        id: "",
        activity_name: "",
        activity_status: 0,
        start_time: "",
        end_time: "",
        city_id: 0,
        activity_owner: "徐辛承",
        district_id: 0
    }
}
