title: Blocks
subtitle: "配置化页面解决方案"
description: "A dragable and configurable platform for repeatability webpages based on Vue2.0."
author: wmfe
language: zh-cn
timezone: UTC

url: https://github.com/wmfe/blocks
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  # repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: blocks
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: blocks
github: wmfe/blocks
