export const DATA_SOURCE_LIST = 'getDataSourceList'
export const DEPARTMENT_INFO = 'getDepartmentInfo'
export const PUSH_PACKAGES = 'getPushPackages'
export const JUMP_TARGET_LIST = 'getJumpTargetList'
export const SET_FORM_PAGE_DATA = 'setFormPageData'
