export const DATA_SOURCE_LIST = 'getDataSourceList'
export const DEPARTMENT_INFO = 'getDepartmentInfo'
export const PUSH_PACKAGES = 'getPushPackages'
export const JUMP_TARGET_LIST = 'getJumpTargetList'
export const SET_FORM_DATA = 'setFormData'
export const SET_FORM_PAGE_DATA = 'setFormPageData'
export const CREATE_PACKAGE_DIALOG = 'createPackageDialog'
export const CLOSE_PACKAGE_DIALOG = 'closePackageDialog'
export const GET_SELECTED_DATA_SOURCES = 'getSelectedDataSource'
export const GET_SELECTED_CITY_IDS = 'getSelectedCityIds'

